# Generated by Django 4.2.9 on 2026-01-12 22:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(help_text='Formato: 1234ABC', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de matrícula inválido. Debe ser: 1234ABC', regex='^[0-9]{4}[BCDFGHJKLMNPRSTVWXYZ]{3}$')], verbose_name='Matrícula')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('color', models.CharField(max_length=30, verbose_name='Color')),
                ('año', models.PositiveIntegerField(verbose_name='Año')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En Uso'), ('MANTENIMIENTO', 'Mantenimiento/Reparación'), ('BAJA', 'Dado de Baja')], default='DISPONIBLE', max_length=15, verbose_name='Estado')),
                ('kilometraje', models.PositiveIntegerField(default=0, help_text='Kilometraje actual del vehículo', verbose_name='Kilometraje')),
                ('fecha_alta', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Alta')),
                ('fecha_ultima_revision', models.DateField(blank=True, null=True, verbose_name='Última Revisión')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre el vehículo', verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['estado', 'matricula'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REVISION', 'Revisión'), ('REPARACION', 'Reparación'), ('ITV', 'ITV'), ('NEUMATICOS', 'Cambio de Neumáticos'), ('OTROS', 'Otros')], max_length=15, verbose_name='Tipo de Mantenimiento')),
                ('fecha_entrada', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Entrada')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='Fecha de Salida')),
                ('descripcion', models.TextField(verbose_name='Descripción del Trabajo')),
                ('coste', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Coste (€)')),
                ('taller', models.CharField(blank=True, max_length=100, verbose_name='Taller/Proveedor')),
                ('completado', models.BooleanField(default=False, verbose_name='Trabajo Completado')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='vehiculos.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha_entrada'],
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100, verbose_name='Cliente/Asignado a')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('kilometraje_salida', models.PositiveIntegerField(verbose_name='Kilometraje de Salida')),
                ('kilometraje_entrada', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometraje de Entrada')),
                ('motivo', models.TextField(verbose_name='Motivo de Asignación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('activa', models.BooleanField(default=True, verbose_name='Asignación Activa')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='vehiculos.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
