# Generated by Django 4.2.9 on 2026-01-13 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='matricula',
            field=models.CharField(help_text='Formato: 0000XXX (4 números + 3 letras)', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de matrícula inválido. Debe ser 4 números seguidos de 3 letras (ej: 0987TRE)', regex='^[0-9]{4}[A-Z]{3}$')], verbose_name='Matrícula'),
        ),
    ]
