# Generated by Django 4.2.9 on 2026-01-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_alter_vehiculo_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_USO', 'En Uso'), ('BAJA', 'Dado de Baja')], default='DISPONIBLE', max_length=15, verbose_name='Estado'),
        ),
        migrations.DeleteModel(
            name='Mantenimiento',
        ),
    ]
